apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azfile-prem-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-prem
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-file
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: evillgenius/dbench
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          # - name: FIO_SIZE
          #   value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: azfile-prem-pvc
  backoffLimit: 4