apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fio-tester-write
  labels:
    purpose: fio-testing-write
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: fio-testing-write
    spec:
      containers:
      - name: fio-container
        image: wallnerryan/fiotools-aio
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: fio-data
          mountPath: /myvol
        env:
          - name: REMOTEFILES
            value: "https://gist.githubusercontent.com/wallnerryan/cb8f9946a6fb9bdc0aabd403d9550e08/raw/31308d8139718901c1b53c9dea33526cf591881d/seqwrite.fio"
          - name: JOBFILES
            value: seqwrite.fio
          - name: PLOTNAME
            value: seqwrite
      volumes:
        - name: fio-data
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: myfs # name of the filesystem specified in the filesystem CRD.
              clusterNamespace: rook-ceph # namespace where the Rook cluster is deployed
              # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
              # the path must exist on the filesystem, otherwise mounting the filesystem at that path will fail
              # path: /some/path/inside/cephfs

---

apiVersion: v1
kind: Service
metadata:
  name: fiotools-write
  labels:
    name: fiotools-write
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: fio-testing-write